// Code generated by go-swagger; DO NOT EDIT.

package service_bindings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ServiceBindingGetHandlerFunc turns a function with the right signature into a service binding get handler
type ServiceBindingGetHandlerFunc func(ServiceBindingGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ServiceBindingGetHandlerFunc) Handle(params ServiceBindingGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ServiceBindingGetHandler interface for that can handle valid service binding get params
type ServiceBindingGetHandler interface {
	Handle(ServiceBindingGetParams, interface{}) middleware.Responder
}

// NewServiceBindingGet creates a new http.Handler for the service binding get operation
func NewServiceBindingGet(ctx *middleware.Context, handler ServiceBindingGetHandler) *ServiceBindingGet {
	return &ServiceBindingGet{Context: ctx, Handler: handler}
}

/*ServiceBindingGet swagger:route GET /v2/service_instances/{instance_id}/service_bindings/{binding_id} ServiceBindings serviceBindingGet

gets a service binding

*/
type ServiceBindingGet struct {
	Context *middleware.Context
	Handler ServiceBindingGetHandler
}

func (o *ServiceBindingGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewServiceBindingGetParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
