// Code generated by go-swagger; DO NOT EDIT.

package service_bindings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ServiceBindingUnbindingHandlerFunc turns a function with the right signature into a service binding unbinding handler
type ServiceBindingUnbindingHandlerFunc func(ServiceBindingUnbindingParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ServiceBindingUnbindingHandlerFunc) Handle(params ServiceBindingUnbindingParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ServiceBindingUnbindingHandler interface for that can handle valid service binding unbinding params
type ServiceBindingUnbindingHandler interface {
	Handle(ServiceBindingUnbindingParams, interface{}) middleware.Responder
}

// NewServiceBindingUnbinding creates a new http.Handler for the service binding unbinding operation
func NewServiceBindingUnbinding(ctx *middleware.Context, handler ServiceBindingUnbindingHandler) *ServiceBindingUnbinding {
	return &ServiceBindingUnbinding{Context: ctx, Handler: handler}
}

/*ServiceBindingUnbinding swagger:route DELETE /v2/service_instances/{instance_id}/service_bindings/{binding_id} ServiceBindings serviceBindingUnbinding

deprovision of a service binding

*/
type ServiceBindingUnbinding struct {
	Context *middleware.Context
	Handler ServiceBindingUnbindingHandler
}

func (o *ServiceBindingUnbinding) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewServiceBindingUnbindingParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
