// Code generated by go-swagger; DO NOT EDIT.

package service_bindings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// ServiceBindingBindingURL generates an URL for the service binding binding operation
type ServiceBindingBindingURL struct {
	BindingID  string
	InstanceID string

	AcceptsIncomplete *bool

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ServiceBindingBindingURL) WithBasePath(bp string) *ServiceBindingBindingURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ServiceBindingBindingURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *ServiceBindingBindingURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/v2/service_instances/{instance_id}/service_bindings/{binding_id}"

	bindingID := o.BindingID
	if bindingID != "" {
		_path = strings.Replace(_path, "{binding_id}", bindingID, -1)
	} else {
		return nil, errors.New("bindingId is required on ServiceBindingBindingURL")
	}

	instanceID := o.InstanceID
	if instanceID != "" {
		_path = strings.Replace(_path, "{instance_id}", instanceID, -1)
	} else {
		return nil, errors.New("instanceId is required on ServiceBindingBindingURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var acceptsIncomplete string
	if o.AcceptsIncomplete != nil {
		acceptsIncomplete = swag.FormatBool(*o.AcceptsIncomplete)
	}
	if acceptsIncomplete != "" {
		qs.Set("accepts_incomplete", acceptsIncomplete)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *ServiceBindingBindingURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *ServiceBindingBindingURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *ServiceBindingBindingURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on ServiceBindingBindingURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on ServiceBindingBindingURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *ServiceBindingBindingURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
