BASE_DIR := $(shell pwd)
BUILD_DIR := $(BASE_DIR)/build

all: build

build: mockbroker

prebuild:
	mkdir -p $(BUILD_DIR)

.PHONY: mockbroker

mockbroker: prebuild
	go build -o $(BUILD_DIR)/osbchecker.mockbroker github.com/openservicebrokerapi/osb-checker/autogenerated/cmd/open-service-broker-server

clean:
	rm -rf $(BUILD_DIR)
