// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/openservicebrokerapi/osb-checker/autogenerated/models"
)

// CatalogGetOKCode is the HTTP code returned for type CatalogGetOK
const CatalogGetOKCode int = 200

/*CatalogGetOK catalog response

swagger:response catalogGetOK
*/
type CatalogGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.Catalog `json:"body,omitempty"`
}

// NewCatalogGetOK creates CatalogGetOK with default headers values
func NewCatalogGetOK() *CatalogGetOK {

	return &CatalogGetOK{}
}

// WithPayload adds the payload to the catalog get o k response
func (o *CatalogGetOK) WithPayload(payload *models.Catalog) *CatalogGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the catalog get o k response
func (o *CatalogGetOK) SetPayload(payload *models.Catalog) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CatalogGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
