package validator

import (
	apiclient "github.com/openservicebrokerapi/osb-checker/autogenerated/client"
	"github.com/openservicebrokerapi/osb-checker/autogenerated/client/catalog"
	bindings "github.com/openservicebrokerapi/osb-checker/autogenerated/client/service_bindings"
	instances "github.com/openservicebrokerapi/osb-checker/autogenerated/client/service_instances"
	"github.com/openservicebrokerapi/osb-checker/constants"
	"github.com/openservicebrokerapi/osb-checker/validator/common"

	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

var val Validator = &validatorV214{
	OpenServiceBroker: apiclient.Default,
	Common:            common.NewValidator(),
}

func init() {
	RegisterValidator(constants.Version214, val)
}

type validatorV214 struct {
	*apiclient.OpenServiceBroker

	Common *common.Validator
}

func (v *validatorV214) Setup(url string) error {
	// create the transport
	transport := httptransport.New(url, "", nil)

	// create the API client, with the transport
	v.OpenServiceBroker = apiclient.New(transport, strfmt.Default)
	v.Common.OpenServiceBroker = apiclient.New(transport, strfmt.Default)

	return nil
}

func (v *validatorV214) GetCatalog(params *catalog.CatalogGetParams) error {
	return nil
}

func (v *validatorV214) Provision(params *instances.ServiceInstanceProvisionParams) error {
	return nil
}

func (v *validatorV214) PollInstanceLastOperation(params *instances.ServiceInstanceLastOperationGetParams) error {
	return nil
}

func (v *validatorV214) GetInstance(params *instances.ServiceInstanceGetParams) error {
	return nil
}

func (v *validatorV214) UpdateInstance(params *instances.ServiceInstanceUpdateParams) error {
	return nil
}

func (v *validatorV214) Deprovision(params *instances.ServiceInstanceDeprovisionParams) error {
	return nil
}

func (v *validatorV214) Bind(params *bindings.ServiceBindingBindingParams) error {
	return nil
}

func (v *validatorV214) PollBindingLastOperation(params *bindings.ServiceBindingLastOperationGetParams) error {
	return nil
}

func (v *validatorV214) GetBinding(params *bindings.ServiceBindingGetParams) error {
	return nil
}

func (v *validatorV214) Unbind(params *bindings.ServiceBindingUnbindingParams) error {
	return nil
}
