// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/openservicebrokerapi/osb-checker/autogenerated/restapi/operations/catalog"
	"github.com/openservicebrokerapi/osb-checker/autogenerated/restapi/operations/service_bindings"
	"github.com/openservicebrokerapi/osb-checker/autogenerated/restapi/operations/service_instances"
)

// NewOpenServiceBrokerAPI creates a new OpenServiceBroker instance
func NewOpenServiceBrokerAPI(spec *loads.Document) *OpenServiceBrokerAPI {
	return &OpenServiceBrokerAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		CatalogCatalogGetHandler: catalog.CatalogGetHandlerFunc(func(params catalog.CatalogGetParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation CatalogCatalogGet has not yet been implemented")
		}),
		ServiceBindingsServiceBindingBindingHandler: service_bindings.ServiceBindingBindingHandlerFunc(func(params service_bindings.ServiceBindingBindingParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ServiceBindingsServiceBindingBinding has not yet been implemented")
		}),
		ServiceBindingsServiceBindingGetHandler: service_bindings.ServiceBindingGetHandlerFunc(func(params service_bindings.ServiceBindingGetParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ServiceBindingsServiceBindingGet has not yet been implemented")
		}),
		ServiceBindingsServiceBindingLastOperationGetHandler: service_bindings.ServiceBindingLastOperationGetHandlerFunc(func(params service_bindings.ServiceBindingLastOperationGetParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ServiceBindingsServiceBindingLastOperationGet has not yet been implemented")
		}),
		ServiceBindingsServiceBindingUnbindingHandler: service_bindings.ServiceBindingUnbindingHandlerFunc(func(params service_bindings.ServiceBindingUnbindingParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ServiceBindingsServiceBindingUnbinding has not yet been implemented")
		}),
		ServiceInstancesServiceInstanceDeprovisionHandler: service_instances.ServiceInstanceDeprovisionHandlerFunc(func(params service_instances.ServiceInstanceDeprovisionParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ServiceInstancesServiceInstanceDeprovision has not yet been implemented")
		}),
		ServiceInstancesServiceInstanceGetHandler: service_instances.ServiceInstanceGetHandlerFunc(func(params service_instances.ServiceInstanceGetParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ServiceInstancesServiceInstanceGet has not yet been implemented")
		}),
		ServiceInstancesServiceInstanceLastOperationGetHandler: service_instances.ServiceInstanceLastOperationGetHandlerFunc(func(params service_instances.ServiceInstanceLastOperationGetParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ServiceInstancesServiceInstanceLastOperationGet has not yet been implemented")
		}),
		ServiceInstancesServiceInstanceProvisionHandler: service_instances.ServiceInstanceProvisionHandlerFunc(func(params service_instances.ServiceInstanceProvisionParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ServiceInstancesServiceInstanceProvision has not yet been implemented")
		}),
		ServiceInstancesServiceInstanceUpdateHandler: service_instances.ServiceInstanceUpdateHandlerFunc(func(params service_instances.ServiceInstanceUpdateParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ServiceInstancesServiceInstanceUpdate has not yet been implemented")
		}),

		// Applies when the Authorization header is set with the Basic scheme
		BasicAuthAuth: func(user string, pass string) (interface{}, error) {
			return nil, errors.NotImplemented("basic auth  (basicAuth) has not yet been implemented")
		},

		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*OpenServiceBrokerAPI The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers. */
type OpenServiceBrokerAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// BasicAuthAuth registers a function that takes username and password and returns a principal
	// it performs authentication with basic auth
	BasicAuthAuth func(string, string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// CatalogCatalogGetHandler sets the operation handler for the catalog get operation
	CatalogCatalogGetHandler catalog.CatalogGetHandler
	// ServiceBindingsServiceBindingBindingHandler sets the operation handler for the service binding binding operation
	ServiceBindingsServiceBindingBindingHandler service_bindings.ServiceBindingBindingHandler
	// ServiceBindingsServiceBindingGetHandler sets the operation handler for the service binding get operation
	ServiceBindingsServiceBindingGetHandler service_bindings.ServiceBindingGetHandler
	// ServiceBindingsServiceBindingLastOperationGetHandler sets the operation handler for the service binding last operation get operation
	ServiceBindingsServiceBindingLastOperationGetHandler service_bindings.ServiceBindingLastOperationGetHandler
	// ServiceBindingsServiceBindingUnbindingHandler sets the operation handler for the service binding unbinding operation
	ServiceBindingsServiceBindingUnbindingHandler service_bindings.ServiceBindingUnbindingHandler
	// ServiceInstancesServiceInstanceDeprovisionHandler sets the operation handler for the service instance deprovision operation
	ServiceInstancesServiceInstanceDeprovisionHandler service_instances.ServiceInstanceDeprovisionHandler
	// ServiceInstancesServiceInstanceGetHandler sets the operation handler for the service instance get operation
	ServiceInstancesServiceInstanceGetHandler service_instances.ServiceInstanceGetHandler
	// ServiceInstancesServiceInstanceLastOperationGetHandler sets the operation handler for the service instance last operation get operation
	ServiceInstancesServiceInstanceLastOperationGetHandler service_instances.ServiceInstanceLastOperationGetHandler
	// ServiceInstancesServiceInstanceProvisionHandler sets the operation handler for the service instance provision operation
	ServiceInstancesServiceInstanceProvisionHandler service_instances.ServiceInstanceProvisionHandler
	// ServiceInstancesServiceInstanceUpdateHandler sets the operation handler for the service instance update operation
	ServiceInstancesServiceInstanceUpdateHandler service_instances.ServiceInstanceUpdateHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *OpenServiceBrokerAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *OpenServiceBrokerAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *OpenServiceBrokerAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *OpenServiceBrokerAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *OpenServiceBrokerAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *OpenServiceBrokerAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *OpenServiceBrokerAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the OpenServiceBrokerAPI
func (o *OpenServiceBrokerAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BasicAuthAuth == nil {
		unregistered = append(unregistered, "BasicAuthAuth")
	}

	if o.CatalogCatalogGetHandler == nil {
		unregistered = append(unregistered, "catalog.CatalogGetHandler")
	}

	if o.ServiceBindingsServiceBindingBindingHandler == nil {
		unregistered = append(unregistered, "service_bindings.ServiceBindingBindingHandler")
	}

	if o.ServiceBindingsServiceBindingGetHandler == nil {
		unregistered = append(unregistered, "service_bindings.ServiceBindingGetHandler")
	}

	if o.ServiceBindingsServiceBindingLastOperationGetHandler == nil {
		unregistered = append(unregistered, "service_bindings.ServiceBindingLastOperationGetHandler")
	}

	if o.ServiceBindingsServiceBindingUnbindingHandler == nil {
		unregistered = append(unregistered, "service_bindings.ServiceBindingUnbindingHandler")
	}

	if o.ServiceInstancesServiceInstanceDeprovisionHandler == nil {
		unregistered = append(unregistered, "service_instances.ServiceInstanceDeprovisionHandler")
	}

	if o.ServiceInstancesServiceInstanceGetHandler == nil {
		unregistered = append(unregistered, "service_instances.ServiceInstanceGetHandler")
	}

	if o.ServiceInstancesServiceInstanceLastOperationGetHandler == nil {
		unregistered = append(unregistered, "service_instances.ServiceInstanceLastOperationGetHandler")
	}

	if o.ServiceInstancesServiceInstanceProvisionHandler == nil {
		unregistered = append(unregistered, "service_instances.ServiceInstanceProvisionHandler")
	}

	if o.ServiceInstancesServiceInstanceUpdateHandler == nil {
		unregistered = append(unregistered, "service_instances.ServiceInstanceUpdateHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *OpenServiceBrokerAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *OpenServiceBrokerAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	result := make(map[string]runtime.Authenticator)
	for name, scheme := range schemes {
		switch name {

		case "basicAuth":
			_ = scheme
			result[name] = o.BasicAuthenticator(o.BasicAuthAuth)

		}
	}
	return result

}

// Authorizer returns the registered authorizer
func (o *OpenServiceBrokerAPI) Authorizer() runtime.Authorizer {

	return o.APIAuthorizer

}

// ConsumersFor gets the consumers for the specified media types
func (o *OpenServiceBrokerAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *OpenServiceBrokerAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *OpenServiceBrokerAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the open service broker API
func (o *OpenServiceBrokerAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *OpenServiceBrokerAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v2/catalog"] = catalog.NewCatalogGet(o.context, o.CatalogCatalogGetHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/v2/service_instances/{instance_id}/service_bindings/{binding_id}"] = service_bindings.NewServiceBindingBinding(o.context, o.ServiceBindingsServiceBindingBindingHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v2/service_instances/{instance_id}/service_bindings/{binding_id}"] = service_bindings.NewServiceBindingGet(o.context, o.ServiceBindingsServiceBindingGetHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v2/service_instances/{instance_id}/service_bindings/{binding_id}/last_operation"] = service_bindings.NewServiceBindingLastOperationGet(o.context, o.ServiceBindingsServiceBindingLastOperationGetHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/v2/service_instances/{instance_id}/service_bindings/{binding_id}"] = service_bindings.NewServiceBindingUnbinding(o.context, o.ServiceBindingsServiceBindingUnbindingHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/v2/service_instances/{instance_id}"] = service_instances.NewServiceInstanceDeprovision(o.context, o.ServiceInstancesServiceInstanceDeprovisionHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v2/service_instances/{instance_id}"] = service_instances.NewServiceInstanceGet(o.context, o.ServiceInstancesServiceInstanceGetHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v2/service_instances/{instance_id}/last_operation"] = service_instances.NewServiceInstanceLastOperationGet(o.context, o.ServiceInstancesServiceInstanceLastOperationGetHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/v2/service_instances/{instance_id}"] = service_instances.NewServiceInstanceProvision(o.context, o.ServiceInstancesServiceInstanceProvisionHandler)

	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/v2/service_instances/{instance_id}"] = service_instances.NewServiceInstanceUpdate(o.context, o.ServiceInstancesServiceInstanceUpdateHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *OpenServiceBrokerAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *OpenServiceBrokerAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *OpenServiceBrokerAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *OpenServiceBrokerAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
