package utils

import (
	"encoding/json"

	v2 "github.com/openservicebrokerapi/osb-checker/autogenerated/models"
	. "github.com/openservicebrokerapi/osb-checker/config"

	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// TODO: For provision, update and bind operation, testCatalogSchema should be
// called to assert the legality of parameters schema.
type SchemaOpts struct {
	ServiceID, PlanID  string
	Parameters         interface{}
	SchemaType, Action string
}

func ParametersSchemaCheck(catalog *v2.Catalog, opt *SchemaOpts) error {
	svc := func(catalog *v2.Catalog) *v2.Service {
		for _, svc := range catalog.Services {
			if *svc.ID == opt.ServiceID {
				return svc
			}
		}
		return nil
	}(catalog)
	plan := func(svc *v2.Service) *v2.Plan {
		for _, plan := range svc.Plans {
			if *plan.ID == opt.PlanID {
				return plan
			}
		}
		return nil
	}(svc)

	// If plan.Schemas is empty, then consider it would success no matter what opt.Parameter is.
	if plan.Schemas == nil {
		return nil
	}
	var params interface{}
	switch opt.SchemaType {
	case TypeServiceInstance:
		// If plan.Schemas.ServiceInstance is empty, then consider it would success no matter
		// what opt.Parameter is.
		instance := plan.Schemas.ServiceInstance
		if instance == nil {
			return nil
		}
		if opt.Action == ActionCreate {
			// If instance.Create is empty, then consider it would success no matter
			// what opt.Parameter is.
			create := instance.Create
			if create == nil {
				return nil
			}
			params = create.Parameters
		} else {
			// If instance.Update is empty, then consider it would success no matter
			// what opt.Parameter is.
			update := instance.Update
			if update == nil {
				return nil
			}
			params = update.Parameters
		}
		break
	case TypeServiceBinding:
		// If plan.Schemas.ServiceBinding is empty, then consider it would success no matter
		// what opt.Parameter is.
		binding := plan.Schemas.ServiceBinding
		if binding == nil {
			return nil
		}
		// If binding.Create is empty, then consider it would success no matter what
		// opt.Parameter is.
		create := binding.Create
		if create == nil {
			return nil
		}
		params = create.Parameters
	}

	schema := new(spec.Schema)
	schemaJSON, _ := json.Marshal(params)
	json.Unmarshal(schemaJSON, schema)
	return validate.AgainstSchema(schema, opt.Parameters, strfmt.Default)
}
