package common

import (
	"context"
	"testing"

	"github.com/antihax/optional"
	openapi "github.com/openservicebrokerapi/osb-checker/autogenerated/go-client"
	. "github.com/openservicebrokerapi/osb-checker/config"
	. "github.com/smartystreets/goconvey/convey"
)

func TestBind(
	t *testing.T,
	instanceID, bindingID string,
	req *openapi.ServiceBindingRequest,
	async bool,
) {
	Convey("BINDING - request syntax", t, func() {

		Convey("should return 412 PreconditionFailed if missing X-Broker-API-Version header", func() {
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingBinding(
				authCtx, "", instanceID, bindingID, openapi.ServiceBindingRequest{},
				&openapi.ServiceBindingBindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldNotBeNil)
			So(resp.StatusCode, ShouldEqual, 412)
		})

		if CONF.Authentication.AuthType != TypeNoauth {
			Convey("should return 401 Unauthorized if missing Authorization header", func() {
				_, resp, err := cli.ServiceBindingsApi.ServiceBindingBinding(
					context.Background(), CONF.APIVersion, instanceID, bindingID,
					openapi.ServiceBindingRequest{},
					&openapi.ServiceBindingBindingOpts{AcceptsIncomplete: optional.NewBool(async)})

				So(err, ShouldNotBeNil)
				So(resp.StatusCode, ShouldEqual, 401)
			})
		}

		if async {
			Convey("should return 422 UnprocessableEntity if missing accepts_incomplete", func() {
				tempBody := openapi.ServiceBindingRequest{}
				deepCopy(req, &tempBody)
				_, resp, err := cli.ServiceBindingsApi.ServiceBindingBinding(
					authCtx, CONF.APIVersion, instanceID, bindingID, tempBody,
					&openapi.ServiceBindingBindingOpts{AcceptsIncomplete: optional.NewBool(false)})

				So(err, ShouldNotBeNil)
				So(resp.StatusCode, ShouldEqual, 422)
			})
		}

		Convey("should reject if missing service_id", func() {
			tempBody := openapi.ServiceBindingRequest{}
			deepCopy(req, &tempBody)
			tempBody.ServiceId = ""
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingBinding(
				authCtx, CONF.APIVersion, instanceID, bindingID, tempBody,
				&openapi.ServiceBindingBindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldNotBeNil)
			So(resp.StatusCode, ShouldEqual, 400)
		})

		Convey("should reject if missing plan_id", func() {
			tempBody := openapi.ServiceBindingRequest{}
			deepCopy(req, &tempBody)
			tempBody.PlanId = ""
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingBinding(
				authCtx, CONF.APIVersion, instanceID, bindingID, tempBody,
				&openapi.ServiceBindingBindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldNotBeNil)
			So(resp.StatusCode, ShouldEqual, 400)
		})

		Convey("should reject if service_id is invalid", func() {
			tempBody := openapi.ServiceBindingRequest{}
			deepCopy(req, &tempBody)
			tempBody.ServiceId = "xxxx-xxxx-xxxx-xxxx"
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingBinding(
				authCtx, CONF.APIVersion, instanceID, bindingID, tempBody,
				&openapi.ServiceBindingBindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldNotBeNil)
			So(resp.StatusCode, ShouldEqual, 400)
		})

		Convey("should reject if plan_id is invalid", func() {
			tempBody := openapi.ServiceBindingRequest{}
			deepCopy(req, &tempBody)
			tempBody.PlanId = "xxxx-xxxx-xxxx-xxxx"
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingBinding(
				authCtx, CONF.APIVersion, instanceID, bindingID, tempBody,
				&openapi.ServiceBindingBindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldNotBeNil)
			So(resp.StatusCode, ShouldEqual, 400)
		})

		Convey("should reject if parameters are not following schema", func() {
			tempBody := openapi.ServiceBindingRequest{}
			deepCopy(req, &tempBody)
			tempBody.Parameters = map[string]interface{}{
				"can-not": "be-good",
			}
			if err := testCatalogSchema(&SchemaOpts{
				ServiceID:  tempBody.ServiceId,
				PlanID:     tempBody.PlanId,
				Parameters: tempBody.Parameters,
				SchemaType: TypeServiceBinding,
				Action:     ActionCreate,
			}); err == nil {
				return
			}
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingBinding(
				authCtx, CONF.APIVersion, instanceID, bindingID, tempBody,
				&openapi.ServiceBindingBindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldNotBeNil)
			So(resp.StatusCode, ShouldEqual, 400)
		})
	})

	Convey("BINDING - new", t, func() {
		Convey("should accept a valid binding request", func() {
			tempBody := openapi.ServiceBindingRequest{}
			deepCopy(req, &tempBody)
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingBinding(
				authCtx, CONF.APIVersion, instanceID, bindingID, tempBody,
				&openapi.ServiceBindingBindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldBeNil)
			if async {
				So(resp.StatusCode, ShouldEqual, 202)
			} else {
				So(resp.StatusCode, ShouldEqual, 201)
			}
		})
	})

	if async {
		Convey("BINDING - poll", t, func(c C) {
			testPollBindingLastOperation(instanceID, bindingID)

			So(pollBindingLastOperationStatus(instanceID, bindingID), ShouldBeNil)
		})
	}

	Convey("BINDING - existed", t, func() {
		Convey("should return 200 OK when binding Id with same instance Id exists with identical properties", func() {
			tempBody := openapi.ServiceBindingRequest{}
			deepCopy(req, &tempBody)
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingBinding(
				authCtx, CONF.APIVersion, instanceID, bindingID, tempBody,
				&openapi.ServiceBindingBindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldBeNil)
			So(resp.StatusCode, ShouldEqual, 200)
		})
	})
}
