package common

import (
	"testing"

	v2 "github.com/openservicebrokerapi/osb-checker/autogenerated/models"
	apiclient "github.com/openservicebrokerapi/osb-checker/client"
	"github.com/openservicebrokerapi/osb-checker/config"
	. "github.com/smartystreets/goconvey/convey"
)

func TestBind(
	t *testing.T,
	instanceID, bindingID string,
	req *v2.ServiceBindingRequest,
	async bool,
) {
	Convey("BINDING - request syntax", t, func() {

		So(testAPIVersionHeader(config.GenerateBindingURL(instanceID, bindingID), "PUT"), ShouldEqual, nil)
		So(testAuthentication(config.GenerateBindingURL(instanceID, bindingID), "PUT"), ShouldEqual, nil)
		if async {
			So(testAsyncParameters(config.GenerateBindingURL(instanceID, bindingID), "PUT"), ShouldEqual, nil)
		}

		var emptyValue, fakeValue = "", "xxxx-xxxx"
		Convey("should reject if missing service_id", func() {
			tempBody := new(v2.ServiceBindingRequest)
			deepCopy(req, tempBody)
			tempBody.ServiceID = &emptyValue
			code, _, _, err := apiclient.Default.Bind(instanceID, bindingID, tempBody)

			So(err, ShouldEqual, nil)
			So(code, ShouldEqual, 400)
		})

		Convey("should reject if missing plan_id", func() {
			tempBody := new(v2.ServiceBindingRequest)
			deepCopy(req, tempBody)
			tempBody.PlanID = &emptyValue
			code, _, _, err := apiclient.Default.Bind(instanceID, bindingID, tempBody)

			So(err, ShouldEqual, nil)
			So(code, ShouldEqual, 400)
		})

		Convey("should reject if service_id is invalid", func() {
			tempBody := new(v2.ServiceBindingRequest)
			deepCopy(req, tempBody)
			tempBody.ServiceID = &fakeValue
			code, _, _, err := apiclient.Default.Bind(instanceID, bindingID, tempBody)

			So(err, ShouldEqual, nil)
			So(code, ShouldEqual, 400)
		})

		Convey("should reject if paln_id is invalid", func() {
			tempBody := new(v2.ServiceBindingRequest)
			deepCopy(req, tempBody)
			tempBody.PlanID = &fakeValue
			code, _, _, err := apiclient.Default.Bind(instanceID, bindingID, tempBody)

			So(err, ShouldEqual, nil)
			So(code, ShouldEqual, 400)
		})

		Convey("should accept a valid binding request", func() {
			tempBody := new(v2.ServiceBindingRequest)
			deepCopy(req, tempBody)
			code, syncBody, asyncBody, err := apiclient.Default.Bind(instanceID, bindingID, tempBody)

			So(err, ShouldEqual, nil)
			if async {
				So(code, ShouldEqual, 202)
				So(testJSONSchema(asyncBody), ShouldEqual, nil)
			} else {
				So(code, ShouldEqual, 201)
				So(testJSONSchema(syncBody), ShouldEqual, nil)
			}

		})

		Convey("should return 200 OK when binding Id with same instance Id exists with identical properties", func() {
			tempBody := new(v2.ServiceBindingRequest)
			deepCopy(req, tempBody)
			code, syncBody, _, err := apiclient.Default.Bind(instanceID, bindingID, tempBody)

			So(err, ShouldEqual, nil)
			So(code, ShouldEqual, 200)
			So(testJSONSchema(syncBody), ShouldEqual, nil)
		})
	})
}
