package common

import (
	"context"
	"testing"

	"github.com/antihax/optional"
	openapi "github.com/openservicebrokerapi/osb-checker/autogenerated/go-client"
	. "github.com/openservicebrokerapi/osb-checker/config"
	. "github.com/smartystreets/goconvey/convey"
)

func TestUnbind(
	t *testing.T,
	instanceID, bindingID string,
	serviceID, planID string,
	async bool,
) {
	Convey("UNBINDING - delete syntax", t, func() {

		Convey("should return 412 PreconditionFailed if missing X-Broker-API-Version header", func() {
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingUnbinding(
				authCtx, "", instanceID, bindingID, serviceID, planID,
				&openapi.ServiceBindingUnbindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldNotBeNil)
			So(resp.StatusCode, ShouldEqual, 412)
		})

		if CONF.Authentication.AuthType != TypeNoauth {
			Convey("should return 401 Unauthorized if missing Authorization header", func() {
				_, resp, err := cli.ServiceBindingsApi.ServiceBindingUnbinding(
					context.Background(), CONF.APIVersion, instanceID, bindingID, serviceID, planID,
					&openapi.ServiceBindingUnbindingOpts{AcceptsIncomplete: optional.NewBool(async)})

				So(err, ShouldNotBeNil)
				So(resp.StatusCode, ShouldEqual, 401)
			})
		}

		if async {
			Convey("should return 422 UnprocessableEntity if missing accepts_incomplete", func() {
				_, resp, err := cli.ServiceBindingsApi.ServiceBindingUnbinding(
					authCtx, CONF.APIVersion, instanceID, bindingID, serviceID, planID,
					&openapi.ServiceBindingUnbindingOpts{AcceptsIncomplete: optional.NewBool(false)})

				So(err, ShouldNotBeNil)
				So(resp.StatusCode, ShouldEqual, 422)
			})
		}

		Convey("should reject if missing service_id", func() {
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingUnbinding(
				authCtx, CONF.APIVersion, instanceID, bindingID, "", planID,
				&openapi.ServiceBindingUnbindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldNotBeNil)
			So(resp.StatusCode, ShouldEqual, 400)
		})

		Convey("should reject if missing plan_id", func() {
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingUnbinding(
				authCtx, CONF.APIVersion, instanceID, bindingID, serviceID, "",
				&openapi.ServiceBindingUnbindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldNotBeNil)
			So(resp.StatusCode, ShouldEqual, 400)
		})
	})

	Convey("UNBINDING - delete", t, func() {
		Convey("should accept a valid service binding deletion request", func() {
			_, resp, err := cli.ServiceBindingsApi.ServiceBindingUnbinding(
				authCtx, CONF.APIVersion, instanceID, bindingID, serviceID, planID,
				&openapi.ServiceBindingUnbindingOpts{AcceptsIncomplete: optional.NewBool(async)})

			So(err, ShouldBeNil)
			if async {
				So(resp.StatusCode, ShouldEqual, 202)
			} else {
				So(resp.StatusCode, ShouldEqual, 200)
			}
		})
	})

	if async {
		Convey("UNBINDING - poll", t, func(c C) {
			testPollBindingLastOperation(instanceID, bindingID)

			So(pollBindingLastOperationStatus(instanceID, bindingID), ShouldBeNil)
		})
	}
}
