package common

import (
	"testing"

	v2 "github.com/openservicebrokerapi/osb-checker/autogenerated/models"
	apiclient "github.com/openservicebrokerapi/osb-checker/client"
	. "github.com/openservicebrokerapi/osb-checker/config"
	. "github.com/smartystreets/goconvey/convey"
)

func TestUpdateInstance(
	t *testing.T,
	instanceID string,
	req *v2.ServiceInstanceUpdateRequest,
	async bool,
) {
	Convey("UPDATE - request syntax", t, func() {

		So(testAPIVersionHeader(GenerateInstanceURL(instanceID), "PATCH"), ShouldEqual, nil)
		So(testAuthentication(GenerateInstanceURL(instanceID), "PATCH"), ShouldEqual, nil)
		So(testAsyncParameters(GenerateInstanceURL(instanceID), "PATCH"), ShouldEqual, nil)

		var tempBody = new(v2.ServiceInstanceUpdateRequest)
		Convey("should reject if missing service_id", func() {
			deepCopy(req, tempBody)
			*tempBody.ServiceID = ""
			code, _, err := apiclient.Default.UpdateInstance(instanceID, tempBody, async)

			So(err, ShouldEqual, nil)
			So(code, ShouldEqual, 400)
		})

		Convey("should reject if service_id is invalid", func() {
			deepCopy(req, tempBody)
			*tempBody.ServiceID = "xxxx-xxxx"
			code, _, err := apiclient.Default.UpdateInstance(instanceID, tempBody, async)

			So(err, ShouldEqual, nil)
			So(code, ShouldEqual, 400)
		})

		Convey("should accept a valid update request", func() {
			deepCopy(req, tempBody)
			code, body, err := apiclient.Default.UpdateInstance(instanceID, tempBody, async)

			So(err, ShouldEqual, nil)
			if async {
				So(code, ShouldEqual, 202)
			} else {
				So(code, ShouldEqual, 200)
			}
			So(testJSONSchema(body), ShouldEqual, nil)
		})
	})
}
