package abstract

import (
	"github.com/openservicebrokerapi/osb-checker/autogenerated/client"
	"github.com/openservicebrokerapi/osb-checker/autogenerated/client/catalog"
	bindings "github.com/openservicebrokerapi/osb-checker/autogenerated/client/service_bindings"
	instances "github.com/openservicebrokerapi/osb-checker/autogenerated/client/service_instances"
)

func NewValidatorV214(edp string) *validatorV214 {
	return &validatorV214{
		OpenServiceBroker: client.Default,
		brokerEndpoint:    edp,
	}
}

type validatorV214 struct {
	*client.OpenServiceBroker

	brokerEndpoint string
}

func (v *validatorV214) GetCatalog(params *catalog.CatalogGetParams) error {
	return nil
}

func (v *validatorV214) Provision(params *instances.ServiceInstanceProvisionParams) error {
	return nil
}

func (v *validatorV214) PollInstanceLastOperation(params *instances.ServiceInstanceLastOperationGetParams) error {
	return nil
}

func (v *validatorV214) GetInstance(params *instances.ServiceInstanceGetParams) error {
	return nil
}

func (v *validatorV214) UpdateInstance(params *instances.ServiceInstanceUpdateParams) error {
	return nil
}

func (v *validatorV214) Deprovision(params *instances.ServiceInstanceDeprovisionParams) error {
	return nil
}

func (v *validatorV214) Bind(params *bindings.ServiceBindingBindingParams) error {
	return nil
}

func (v *validatorV214) PollBindingLastOperation(params *bindings.ServiceBindingLastOperationGetParams) error {
	return nil
}

func (v *validatorV214) GetBinding(params *bindings.ServiceBindingGetParams) error {
	return nil
}

func (v *validatorV214) Unbind(params *bindings.ServiceBindingUnbindingParams) error {
	return nil
}
