// Code generated by go-swagger; DO NOT EDIT.

package service_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ServiceInstanceProvisionHandlerFunc turns a function with the right signature into a service instance provision handler
type ServiceInstanceProvisionHandlerFunc func(ServiceInstanceProvisionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ServiceInstanceProvisionHandlerFunc) Handle(params ServiceInstanceProvisionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ServiceInstanceProvisionHandler interface for that can handle valid service instance provision params
type ServiceInstanceProvisionHandler interface {
	Handle(ServiceInstanceProvisionParams, interface{}) middleware.Responder
}

// NewServiceInstanceProvision creates a new http.Handler for the service instance provision operation
func NewServiceInstanceProvision(ctx *middleware.Context, handler ServiceInstanceProvisionHandler) *ServiceInstanceProvision {
	return &ServiceInstanceProvision{Context: ctx, Handler: handler}
}

/*ServiceInstanceProvision swagger:route PUT /v2/service_instances/{instance_id} ServiceInstances serviceInstanceProvision

provision a service instance

*/
type ServiceInstanceProvision struct {
	Context *middleware.Context
	Handler ServiceInstanceProvisionHandler
}

func (o *ServiceInstanceProvision) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewServiceInstanceProvisionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
