// Code generated by go-swagger; DO NOT EDIT.

package service_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/openservicebrokerapi/osb-checker/autogenerated/models"
)

// ServiceInstanceUpdateOKCode is the HTTP code returned for type ServiceInstanceUpdateOK
const ServiceInstanceUpdateOKCode int = 200

/*ServiceInstanceUpdateOK OK

swagger:response serviceInstanceUpdateOK
*/
type ServiceInstanceUpdateOK struct {

	/*
	  In: Body
	*/
	Payload models.Object `json:"body,omitempty"`
}

// NewServiceInstanceUpdateOK creates ServiceInstanceUpdateOK with default headers values
func NewServiceInstanceUpdateOK() *ServiceInstanceUpdateOK {

	return &ServiceInstanceUpdateOK{}
}

// WithPayload adds the payload to the service instance update o k response
func (o *ServiceInstanceUpdateOK) WithPayload(payload models.Object) *ServiceInstanceUpdateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the service instance update o k response
func (o *ServiceInstanceUpdateOK) SetPayload(payload models.Object) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ServiceInstanceUpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ServiceInstanceUpdateAcceptedCode is the HTTP code returned for type ServiceInstanceUpdateAccepted
const ServiceInstanceUpdateAcceptedCode int = 202

/*ServiceInstanceUpdateAccepted Accepted

swagger:response serviceInstanceUpdateAccepted
*/
type ServiceInstanceUpdateAccepted struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceInstanceAsyncOperation `json:"body,omitempty"`
}

// NewServiceInstanceUpdateAccepted creates ServiceInstanceUpdateAccepted with default headers values
func NewServiceInstanceUpdateAccepted() *ServiceInstanceUpdateAccepted {

	return &ServiceInstanceUpdateAccepted{}
}

// WithPayload adds the payload to the service instance update accepted response
func (o *ServiceInstanceUpdateAccepted) WithPayload(payload *models.ServiceInstanceAsyncOperation) *ServiceInstanceUpdateAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the service instance update accepted response
func (o *ServiceInstanceUpdateAccepted) SetPayload(payload *models.ServiceInstanceAsyncOperation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ServiceInstanceUpdateAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ServiceInstanceUpdateBadRequestCode is the HTTP code returned for type ServiceInstanceUpdateBadRequest
const ServiceInstanceUpdateBadRequestCode int = 400

/*ServiceInstanceUpdateBadRequest Bad Request

swagger:response serviceInstanceUpdateBadRequest
*/
type ServiceInstanceUpdateBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewServiceInstanceUpdateBadRequest creates ServiceInstanceUpdateBadRequest with default headers values
func NewServiceInstanceUpdateBadRequest() *ServiceInstanceUpdateBadRequest {

	return &ServiceInstanceUpdateBadRequest{}
}

// WithPayload adds the payload to the service instance update bad request response
func (o *ServiceInstanceUpdateBadRequest) WithPayload(payload *models.Error) *ServiceInstanceUpdateBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the service instance update bad request response
func (o *ServiceInstanceUpdateBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ServiceInstanceUpdateBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ServiceInstanceUpdateUnprocessableEntityCode is the HTTP code returned for type ServiceInstanceUpdateUnprocessableEntity
const ServiceInstanceUpdateUnprocessableEntityCode int = 422

/*ServiceInstanceUpdateUnprocessableEntity Unprocessable entity

swagger:response serviceInstanceUpdateUnprocessableEntity
*/
type ServiceInstanceUpdateUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewServiceInstanceUpdateUnprocessableEntity creates ServiceInstanceUpdateUnprocessableEntity with default headers values
func NewServiceInstanceUpdateUnprocessableEntity() *ServiceInstanceUpdateUnprocessableEntity {

	return &ServiceInstanceUpdateUnprocessableEntity{}
}

// WithPayload adds the payload to the service instance update unprocessable entity response
func (o *ServiceInstanceUpdateUnprocessableEntity) WithPayload(payload *models.Error) *ServiceInstanceUpdateUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the service instance update unprocessable entity response
func (o *ServiceInstanceUpdateUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ServiceInstanceUpdateUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
