// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Open Service Broker API
The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: v2.13
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: Open Service Broker API<open-service-broker-api@googlegroups.com> https://www.openservicebrokerapi.org/

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
